version: '3'

services:

  ssr_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: docker/bin/run_ssr_api.sh
    volumes:
      - ../:/usr/src/app
    ports:
      - '8000:8000'
    links:
      - postgres
    depends_on:
      - postgres
    entrypoint: /entrypoint.sh

  ssr_celery:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: docker/bin/run_ssr_celery.sh
    volumes:
      - ../:/usr/src/app
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    entrypoint: /entrypoint.sh
