# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterequest',
            name='response_code',
            field=models.IntegerField(null=True),
        ),
    ]
